<?php

/**
 * @file
 * Contains client_side_file_crypto.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function client_side_file_crypto_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the client_side_file_crypto module.
    case 'help.page.client_side_file_crypto':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Client side crypto for files for a zero knowledge system') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function client_side_file_crypto_theme() {
  return [
    'client_side_file_crypto' => [
      'render element' => 'children',
    ],
  ];
}
