<?php

/**
 * @file
 * Contains client_side_file_crypto.module.
 */

use Drupal\Core\Form\FormState;
use Drupal\user\Entity\User;
use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function client_side_file_crypto_form_user_login_form_alter(&$form, FormState $form_state) {
  $form['#submit'][] = 'client_side_file_crypto_user_login_submit';
}

/**
 * Implements hook_page_attachments().
 */
function client_side_file_crypto_page_attachments(&$page) {
  $user = \Drupal::currentUser();
  $page['#attached']['drupalSettings']['client_side_file_crypto']['uid'] = $user->id();
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function client_side_file_crypto_form_node_article_form_alter(&$form, &$form_state, $form_id) {
  $form['#submit'][] = 'client_side_file_crypto_node_article_form_submit';
  $form['#attached'] = [
    'library' => [
      'client_side_file_crypto/csfcEncrypt',
    ],
  ];
  $form['cryptoFields'] = [
    '#type' => 'file',
    '#title' => t('Encrypted file'),
    '#id' => 'cryptoFields',
    '#weight' => 15,
    '#description' => t('Attach your file with sensitive data here.'),
  ];
  $form['fileID'] = [
    '#type' => 'hidden',
    '#id' => 'fileID',
    '#title' => t('Encrypted file ID'),
    '#weight' => 14,
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Attaches post submission method to node form.
 */
function client_side_file_crypto_form_node_form_alter(&$form, FormState $form_state, $form_id) {
  foreach (array_keys($form['actions']) as $action) {
    if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'client_side_file_crypto_form_submit';
    }
  }
}

/**
 * Form submission handler for node_article_form().
 *
 * Encrypted file upload link for new node.
 */
function client_side_file_crypto_form_submit(array $form, FormState $form_state) {
  $query = \Drupal::database()->update('client_side_file_crypto_files');
  $query->fields([
    'nodeID' => $form_state->getValue('nid'),
  ]);
  $query->condition('fileIndex', $form_state->getValue('fileID'));
  $query->execute();
}

/**
 * Form submission handler for user_login_form().
 *
 * Conditional redirect post login handler.
 */
function client_side_file_crypto_user_login_submit(&$form, FormState $form_state) {
  $uid = \Drupal::currentUser()->id();
  $user = User::load($uid);
  $pubKeyAvailable = $user->get('pub_key')->value;
  if ($pubKeyAvailable != NULL || $pubKeyAvailable != "") {
    $url = Url::fromRoute('client_side_file_crypto.postLogin');
  }
  else {
    $url = Url::fromRoute('client_side_file_crypto.newKeys');
  }
  $request = \Drupal::service('request_stack')->getCurrentRequest();
  if (!$request->request->has('destination')) {
    $form_state->setRedirectUrl($url);
  }
  else {
    $request->query->set('destination', $request->request->get('destination'));
  }
}

/**
 * Implements hook_help().
 */
function client_side_file_crypto_help($route_name, RouteMatchInterface $route_match) {

  switch ($route_name) {
    // Main module help for the client_side_file_crypto module.
    case 'help.page.client_side_file_crypto':
      $output = '';
      $output .= '<h2>' . t('Client-side File encryption for implementing a zero-knowledge system') . '</h2>';
      $output .= '<h4>' . t('Google Summer of Code Project for Drupal') . '</h4>';
      $output .= '<h4>' . t('Student: Tameesh Biswas (@tameeshb)') . '</h4>';
      $output .= '<h4>' . t('Mentor: Colan Schwartz (@colan)') . '</h4>';
      $output .= '<h4>' . t('Objective') . '</h4>';
      $output .= '<p>' . t('This project will involve building a complete module for Drupal 8 site to make it a zero-knowledge system using client-side encryption so that the users can rely on the site when uploading sensitive files, including images on confidential posts, not having to worry about data being stolen in case the server gets compromised.') . '</p>';
      $output .= '<p>' . t('Client side crypto for files for a zero knowledge system') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function client_side_file_crypto_theme() {
  return [
    'client_side_file_crypto' => [
      'render element' => 'children',
    ],
  ];
}
